//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDipEducationCollegeOfficial.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class StudentTbl
    {
        [Display(Name = "Student ID")]
        public string StudentID { get; set; }

        [Display(Name = "Name")]
        public string StudentName { get; set; }

        [Display(Name = "PPS Number")]
        public string PPSNumber { get; set; }
    }
}
